name: Sync

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'yanglbme/gitee-pages-action'
    steps:
      - name: Sync to Gitee
        uses: zhangyuchaoren/shenhaicool@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@gitee.com:zhangyuchaoren/shenhaicool.git
          destination-repo: git@gitee.com:zhangyuchaoren/shenhaicool.git
